name: Deploy my blog to AWS Lambda

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default: Allen

permissions:
  id-token: write
  contents: read

jobs:
  deploy-laravel-to-lambda:
    name: Deploy my blog to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        # https://github.com/aws-actions/configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::154471991214:role/github_action
          aws-region: us-west-2

      - name: Setup php
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.8.0"

      - name: Setup terraform
        # https://github.com/hashicorp/setup-terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy to AWS Lambda
        run: |
          git clone "${{ vars.BLOG_APP_GITHUB_URL }}" laravel-app

          cd laravel-app

          # install composer dependencies
          composer install --prefer-dist --optimize-autoloader --no-dev
          php artisan optimize
          php artisan config:clear
          php artisan feed:install

          # generate front-end assets
          npm install
          npm run build

          # enable bref pgsql extension in lambda if you need it
          # https://bref.sh/docs/environment/php#extensions-installed-but-disabled-by-default
          # mkdir -p php/conf.d
          # echo "extension=pdo_pgsql" > php/conf.d/pgsql.ini

          # remove unnecessary files
          rm -rf node_modules
          rm -rf public/storage
          rm -rf resources/assets
          rm -rf resources/css
          rm -rf resources/images
          rm -rf resources/js
          rm -rf resources/ts
          rm -rf storage
          rm -rf tests
          rm -rf .git
          rm -rf .github

          # zip the laravel app
          zip -r "../laravel-app.zip" .

          cd ..

          # create environment variables json file
          echo '${{ secrets.BLOG_ENVIRONMENT_VARIABLES_JSON }}' > environment-variables.json

          # create terraform config file
          cat <<EOF > terraform.config
          bucket="us-west-2-terraform-state-storage"
          key="us-west-2-blog-serverless.tfstate"
          region="us-west-2"
          dynamodb_table="us-west-2-terraform-state-locking"
          EOF

          # create terraform.tfvars file
          cat <<EOF > terraform.tfvars
          app_name="${{ vars.BLOG_APP_NAME }}"

          # VPC settings
          enable_vpc         = true
          subnet_ids         = ${{ vars.BLOG_SUBNET_IDS }}
          security_group_ids = ${{ vars.BLOG_SECURITY_GROUP_IDS }}

          # File storage settings
          enable_filesystem = true
          access_point_arn  = "${{ vars.BLOG_ACCESS_POINT_ARN }}"

          # api gateway settings
          certificate_arn    = "${{ vars.BLOG_CERTIFICATE_ARN }}"
          custom_domain_name = "${{ vars.BLOG_CUSTOM_DOMAIN_NAME }}"

          # provider settings
          tag_service     = "${{ vars.BLOG_TAG_SERVICE }}"
          tag_environment = "${{ vars.BLOG_TAG_ENVIRONMENT }}"
          tag_owner       = "${{ vars.BLOG_TAG_OWNER }}"

          # S3 bucket settings
          aws_bucket = "${{ vars.BLOG_AWS_BUCKET }}"

          # Lambda settings
          environment_variables_json_file = "./environment-variables.json"

          filename = "./laravel-app.zip"
          EOF

          # deploy
          terraform init -backend-config="./terraform.config"
          terraform apply -auto-approve

          # sync front-end assets to s3 bucket
          aws s3 sync laravel-app/public "s3://${{ vars.BLOG_ASSET_AWS_BUCKET }}"
